// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace ScraperAPI.Migrations
{
    [DbContext(typeof(ScrapingEngineDbContext))]
    [Migration("20251231100143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ScraperAPI.Models.JobQuery", b =>
                {
                    b.Property<int>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("QhighSalary")
                        .HasColumnType("money")
                        .HasColumnName("QHighSalary");

                    b.Property<TimeOnly>("QjobEndTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new TimeOnly(17, 0, 0))
                        .HasColumnName("QJobEndTime");

                    b.Property<string>("QjobLocation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Amman, Jordan")
                        .HasColumnName("QJobLocation");

                    b.Property<string>("QjobName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Software Developer")
                        .HasColumnName("QJobName");

                    b.Property<TimeOnly>("QjobStartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new TimeOnly(9, 0, 0))
                        .HasColumnName("QJobStartTime");

                    b.Property<decimal>("QlowSalary")
                        .HasColumnType("money")
                        .HasColumnName("QLowSalary");

                    b.Property<string>("QueryDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueryId");

                    b.HasIndex(new[] { "UserId" }, "IX_JobQueries_UserId");

                    b.ToTable("JobQueries");
                });

            modelBuilder.Entity("ScraperAPI.Models.JobSite", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("SiteId");

                    b.ToTable("JobSites");
                });

            modelBuilder.Entity("ScraperAPI.Models.ScrapedJob", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobLocation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("QueryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobId");

                    b.HasIndex(new[] { "QueryId" }, "IX_ScrapedJobs_QueryId");

                    b.HasIndex(new[] { "SiteId" }, "IX_ScrapedJobs_SiteId");

                    b.ToTable("ScrapedJobs");
                });

            modelBuilder.Entity("ScraperAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserMajor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "UserEmail" }, "IX_Users_Email");

                    b.HasIndex(new[] { "UserEmail" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScraperAPI.Models.JobQuery", b =>
                {
                    b.HasOne("ScraperAPI.Models.User", "User")
                        .WithMany("JobQueries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_JobQueries_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScraperAPI.Models.ScrapedJob", b =>
                {
                    b.HasOne("ScraperAPI.Models.JobQuery", "Query")
                        .WithMany("ScrapedJobs")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ScrapedJobs_JobQueries");

                    b.HasOne("ScraperAPI.Models.JobSite", "Site")
                        .WithMany("ScrapedJobs")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ScrapedJobs_JobSites");

                    b.Navigation("Query");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ScraperAPI.Models.JobQuery", b =>
                {
                    b.Navigation("ScrapedJobs");
                });

            modelBuilder.Entity("ScraperAPI.Models.JobSite", b =>
                {
                    b.Navigation("ScrapedJobs");
                });

            modelBuilder.Entity("ScraperAPI.Models.User", b =>
                {
                    b.Navigation("JobQueries");
                });
#pragma warning restore 612, 618
        }
    }
}
